# Generated by Django 5.0.6 on 2025-01-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_role_delete_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagramaccount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profilepicture',
        ),
    ]
